channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - scipy
  - numpy
  - matplotlib
  - ipympl
  - pip
  - jupyterlab_vim
  - mpl-interactions
  - pip:
      - black
      - isort
      - jupyterlab-vimrc
      - jupyterlab_code_formatter
      - theme-darcula
name: base
